WebBook/WebBook/urls.py
#from django import views
from django.contrib import admin
from django.urls import include, path
from catalog import views
#from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
  path('', include('catalog.urls')),  # если в запросе пустая строка, произайдёт переодресация в файл ...
  path('admin/', admin.site.urls),
]


# Работа с mediafile локально
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

WebBook/catalog/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
]

WebBook/catalog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Gener(models.Model):
    name = models.CharField(
        max_length=200, verbose_name="Жанр книг", help_text="Введите жанр книги"
    )

    def __str__(self) -> str:
        return self.name


class Language(models.Model):
    name = models.CharField(
        max_length=20, verbose_name="Язык книги", help_text="Введите язык книги"
    )

    def __str__(self) -> str:
        return self.name


class Publisher(models.Model):
    name = models.CharField(
        max_length=20,
        help_text="Введите наименование издательства",
        verbose_name="Издательства",
    )

    def __str__(self) -> str:
        return self.name


class Author(models.Model):
    first_name = models.CharField(
        max_length=100, help_text="Введите имя автора", verbose_name="Имя автора"
    )

    last_name = models.CharField(
        max_length=100,
        help_text="Введите фамилию автора",
        verbose_name="Фамилия автора",
    )

    surname = models.CharField(
        max_length=100,
        help_text="Введите отчество автора(если есть)",
        verbose_name="Фамилия отчество",
        null=True,
        blank=True,
    )

    date_of_birth = models.DateField(
        help_text="Введите дату рождения",
        verbose_name="Дата рождения",
        null=True,
        blank=True,
    )

    about = models.TextField(
        help_text="Введите сведения об авторе",
        verbose_name="Сведения об авторе",
        null=True,
        blank=True,
    )

    photo = models.ImageField(
        upload_to="images",
        help_text="Прекрепите фото автора(если есть)",
        verbose_name="Фото автора",
        null=True,
        blank=True,
    )

    def __str__(self) -> str:
        return self.last_name


class Book(models.Model):
    title = models.CharField(
        max_length=200,
        help_text="Введите название книги",
        verbose_name="Название книги",
    )

    gener = models.ForeignKey(
        "Gener",
        on_delete=models.CASCADE,
        help_text="Введите жанр для книги",
        verbose_name="Жанр книги",
        null=True,
    )

    language = models.ForeignKey(
        "language",
        on_delete=models.CASCADE,
        help_text="Введите язык для книги",
        verbose_name="Язык книги",
        null=True,
    )

    publisher = models.ForeignKey(
        "Publisher",
        on_delete=models.CASCADE,
        help_text="Выберите язык издательство",
        verbose_name="Издательство",
        null=True,
    )

    year = models.CharField(
        max_length=4, help_text="Введите год издания", verbose_name="Год издания"
    )

    author = models.ManyToManyField(
        "Author",
        help_text="Выберите автора(авторов) книги",
        verbose_name="Автор(аворы) книги",
    )

    summary = models.TextField(
        max_length=1000,
        help_text="Введите краткое описание книги",
        verbose_name="Аннотация книги",
    )

    isbn = models.CharField(
        max_length=13,
        help_text="Должно содержать 13 символов",
        verbose_name="ISBN книги",
    )

    price = models.DecimalField(
        decimal_places=2,
        max_digits=7,
        help_text="Введите цену книги",
        verbose_name="Цена (руб.)",
    )

    photo = models.ImageField(
        upload_to="images",
        help_text="Вставте изображение обложки книги",
        verbose_name="Изображение обложки",
        blank=True, null=True 
    )

    photo_url = models.CharField(
        max_length=200,
        help_text="URL-photo",
        verbose_name="URL-photo",
        blank=True, null=True
    )

    def __str__(self) -> str:
        return self.title


    def get_absolute_url(self):
        """Возврощает URL-адрес для доступа к определённому экземпляру книги"""
        return reverse("book_detail", args=[str(self.id)])
    

    def display_author(self):
        return ', '.join([author.last_name for author in self.author.all()])
    
    display_author.short_description = 'Авторы'


class Status(models.Model):
    name = models.CharField(
        max_length=20,
        help_text="Введите статус экземпляра книге",
        verbose_name="Статус экземпляра книге",
    )

    def __str__(self) -> str:
        return self.name


class BookInstance(models.Model):
    book = models.ForeignKey("Book", on_delete=models.CASCADE, null=True)

    status = models.ForeignKey(
        "Status",
        on_delete=models.CASCADE,
        null=True,
        help_text="Изменить состояние экземпляра",
        verbose_name="Cтaтyc экземпляра книги",
    )

    inv_nom = models.CharField(
        max_length=20,
        null=True,
        help_text="Введите инвентарный номер экземпляра",
        verbose_name="Инвентарный номер",
    )

    due_back = models.DateField(
        null=True,
        blank=True,
        help_text="Введите конец срока статуса",
        verbose_name="Дaтa окончания статуса",
    )

    # Метoданные
    class Meta:
        """Сортировка экз. книги(по дате окончание(due_back))"""

        ordering = ["due_back"]

    def __str__(self) -> str:
        """Неформальный вывод экз. книги по шаблону"""
        return "%s %s %s" % (self.inv_nom, self.book, self.status)

WebBook/catalog/views.py
# from cgitb import html
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render
#from django.http import HttpResponse
#from django.template import context
from .models import Book, Author, BookInstance
from django.views.generic import ListView, DetailView
# Create your views here.


def index(request):
    """Словарь для передачи данных в шаблон"""
    text_head = 'Главная страница сайта "World Books"!'

    """Данные о книгах и их количестве"""
    books = Book.objects.all()
    count_all_books = Book.objects.all().count()

    """Данные об экземплярах книг в БД"""
    count_all_instances = Book.objects.all().count()

    """Доступные книги (статус = 'На складе')"""
    count_instances_available = BookInstance.objects.filter(status__exact=1).count()

    """Данные об авторах книг"""
    author = Author.objects
    count_all_authors = Author.objects.count()
    

    """Словарь для передачи данных в шаблон index.htm"""
    contexts = {
        "text_head": text_head,
        "books": books,
        "count_all_books": count_all_books,
        "count_all_instances": count_all_instances,
        "count_instances_available": count_instances_available,
        "author": author,
        "count_all_authors": count_all_authors,
    }

    return render(request, "catalog/index.html", context=contexts)


class BookListView(ListView):
    model = Book
    context_object_name = 'books'
    paginate_by = 5


class BookDetailView(DetailView):
    model = Book
    context_object_name = 'book' # --- поумочанию  равен objects
    #template_name = 'detail_book.html' # --- здаётся html шаблон

WebBook/templates/catalog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">


  <link rel="stylesheet" type="text/css" href="{% static '\styles\style.css' %}">

  <link rel="stylesheet" href="{% static '\css\bootstrap.min.css' %}">

  <script defer src="{%static '\js\bootstrap.bundle.min.js' %}"></script>

  <title>{% block title %}  {% endblock title %}</title>

</head>

<style>
  
</style>


<body>
  
 <header class="">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
          <a class="nav-link" href="#">Features</a>
          <a class="nav-link" href="#">Pricing</a>
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </div>
      </div>
    </div>
  </nav>
 </header>

 <div class="container-fluid navigate-bar">
  <div class="row text-center">
    <div class="col">
      <a href="{% url "index" %}">Главная страница</a>
    </div>
    <div class="col">
      <a href="{% url "index" %}">О комnании</a>
    </div>
    <div class="col">
      <a href="{% url "index" %}">Контакты</a>
    </div>
  </div>
 </div>
  

 {% block main-page %}

 {% endblock main-page %}
  


  <div class="container-fluid content-block" >
    <div class="row text-center text-body">
      <div class="col-2" style="border-right: 2px solid grey;">


        {% block sidebar %}
        <nav class="flex-column nav">

          <a class="nav-link" href="{% url "books" %}">Все книги</a>
          <a class="nav-link" href="{% url "index" %}">Все авторы</a>

        </nav>
        {% endblock sidebar %}


      </div>

      <div class="col-10">
        <div class="row text-center">
          {% block content %}

          {% endblock content %}

{% comment %} =================== Пагинатор ========================== {% endcomment %}

          <div class="paginator">
            <span class="step-links">
            {% if page_obj.paginator.num_pages > 1 %}
                {% if page_obj.has_previous %}
                  <a href="?page=1">Первая</a>
                  <a href="?page={{page_obj.has_previous_page_number}}">Предыдущая</a>
                {% endif %}

                <span class="current">
                  Стр. {{page_obj.number}}
                    из {{page_obj.paginator.num_pages}}
                </span>

                {% if page_obj.has_next %}
                  <a href="?page={{page_obj.next_page_number}}">Следущая</a>
                  <a href="?page={{page_obj.paginator.num_pages}}">Предыдущая &raquo;</a>                
                {% endif %}

            {% endif %}
            </span>
          </div>
{% comment %} =================== Пагинатор ========================== {% endcomment %}

        </div>
      </div>
      

    </div>
  </div>




  <footer>
    <div class="b-example-divider">

      <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
          <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
              <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
            </a>
            <span class="mb-3 mb-md-0 text-muted">&copy; 2022 Company, Inc</span>
          </div>

          <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
            <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
            <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
          </ul>
        </footer>
      </div>
    </div>

    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="bootstrap" viewBox="0 0 118 94">
        <title>Bootstrap</title>
        <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
      </symbol>
      <symbol id="facebook" viewBox="0 0 16 16">
        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
      </symbol>
      <symbol id="instagram" viewBox="0 0 16 16">
          <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
      </symbol>
      <symbol id="twitter" viewBox="0 0 16 16">
        <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
      </symbol>
    </svg>

  </footer>


  




</body>
</html>

WebBook/templates/catalog/book_detail.html
{% extends "catalog/base.html" %}
{% load static %}
{% block title %}Мир книг{% endblock title %}






{% block content %}
<div class="container text-start">
  <div class="row my-2">
    <h3> Название книги - {{book.title}} </h3>
  </div>
  

  <div class="row my-2">
    <p> <strong> Авторы: </strong> </p>
    {% for author in book.author.all %}
      <a href="#">{{author.first_name}} {{author.last_name}}</a>
    {% endfor %}
  </div>


  <img src="{{ book.photo_url }}" alt="conect" style="max-height: 400px">
  <a href="{{ book.photo_url }}" class="btn btn-primary" target="_blank">Показать</a>


  <div class="row my-2">
    <div class="col">
      <p>Цена: <strong>{{book.price}}</strong> руб.</p>
    </div>
  </div>

  <div class="row my-2">
    <div class="col">
      <p><strong>Аннотация:</strong> {{book.summary}}</p>
    </div>
  </div>


  <div class="row my-2 d-flex justify-content-around">
    <div class="col-2 mx-2 bg-primary text-white" >
      <p><strong>Жанр:</strong> {{book.gener}}</p>
    </div>   
    <div class="col-2 mx-2 bg-primary text-white">
      <p><strong>ISBN:</strong> {{book.isbn}}</p>
    </div>
    <div class="col-2 mx-2 bg-primary text-white">
      <p><strong>Язык:</strong> {{book.language}}</p>
    </div>
    <div class="col-2 mx-2 bg-primary text-white">
      <p><strong>Издательство:</strong> {{book.publisher}}</p>
    </div>
  </div>

  <div style="margin-left: 20px; margin-top: 10px;">
    <h4>Количество экземпляров книг в БД</h4>
    {% for copy in book.bookinstance_set.all %}
    <hr>
      <p class="text-muted">
        <strong>Инвентарный нoмep:</strong> {{copy.id}}
      </p>
      <p class="text-success">
        <strong>Cтaтус экземпляра книги:</strong> {{copy.status}}</p>
      </p>
    {% endfor %}
  </div>


</div>

{% endblock content %}

WebBook/templates/catalog/book_list.html
{% extends "catalog/base.html" %}
{% load static %}
{% block title %}Мир книг{% endblock title %}



{% block content %}
  <div class="row text-center text-dark lh-2">
    <h4>Список книг в БД</h4>
  </div>

  {% if books %}
    <table class="table table-striped table-bordered text-start">
      <thead>
        <tr>
          <th>Название</th>
          <th>Автор</th>
          <th>Жанр</th>
          <th>Обложка</th>
          <th>Показать обложку</th>         
        </tr>
      </thead>

      <tbody>
        {% for book in books %}

          <tr>
            <td><a href="{{ book.id }}">{{ book.title }}</a></td>
            <td>{{ book.display_author }}</td>
            <td>{{ book.gener }}</td>
            {% if book.photo_url %}
              <td><img src="{{book.photo_url}}" alt="..." style="max-height: 100px;"></td>
              <td><a href="{{book.photo_url}}" class="btn btn-primary">Показать</a></td>
            {% else %}
            <td colspan='2'>Фото не найдено</td>

            
            {% endif %}
            
          </tr>

        {% endfor %}
      </tbody>
    </table>

  {% else %}
    <p>В базе данных нет книг</p>
  {% endif %}

{% endblock content %}

WebBook/templates/catalog/index.html
{% extends "catalog/base.html" %}
{% load static %}
{% block title %}Мир книг{% endblock title %}




{% block main-page %}
  <div class="main image" style="
    background: 
    linear-gradient(rgba(255, 255, 255, 0.4), rgba(0, 0, 0, 0.7)), 
    url({% static 'images/istockphoto-1320176241-2048x2048-transformed.jpeg' %});
    background-size: cover;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-position: top; ">

      {% comment %} <div class="row main-page" style="background-image: url({% static 'images/istockphoto-1320176241-2048x2048-transformed.jpeg' %});background-size: cover; background-position: center; background-color: rgba(0, 0, 0, .5);"> {% endcomment %}

    <div class="container">    
      <div class="row main-page">

        <div class="col text-center fs-1 fw-bold title-page">
          <div class="title-page">{% block header %} <h5 class="title-page blur"> {{ text_head }} </h5> {% endblock header %}</div>
        </div>

      </div>
    </div>
  </div>
{% endblock main-page %}




{% block content %}
<style>
  
</style>


  <div class="container">
    <div class="row">

      <div class="col text-center">
        <div>
          <p>
            Добро пожаловать на сайт <em>Мир книг</em>. Это очень
            простой веб-сайт, написанный на Django и Bootstrap.
            Разработан на Python в качестве учебного примера
            с использованием PyCharm.
          </p>
        </div>
      </div>
    </div>

    <div class="row text-center text-dark lh-2">
      <h4>Сведения из базы данных</h4>
    </div>

    <div class="row my-2">
      <div class="col mx-2">
        Количество книг - {{ count_all_books }}
      </div>

      <div class="col mx-2">
        Нa складе в наличии - {{ count_instances_available }}
      </div>

      <div class="col mx-2">
        Количество авторов - {{ count_all_authors }}
      </div>
    </div>

    <div class="row text-center text-dark lh-2">
      <h3>Книги</h3>
    </div>

    {% if count_all_books > 0 %}
      <div class="row my-5">
        {% for obj in books %}
          {% if  obj.photo_url %}
            <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12">
              <div class="card card-book" style='display: inline-block;'>
                <img src="{{ obj.photo_url }}" class="card-img-top" alt="..." width="286px" height="369px">
                <div class="card-body">
                  <h5 class="card-title" style="height: 170px;">
                    {{ obj.title }}
                  </h5>
                  
                  <div class="price-book">
                    <p class="card-text small">
                      Цена: <strong><em>{{ obj.price }}</em></strong> руб.
                    </p>

                    <a href="books/{{ obj.id }}" class="btn btn-primary">Подробнее о книге</a>
                  </div>

                </div>
              </div>
            </div>
          {% endif %}
        {% endfor %}

      </div>
    {% endif %}


  </div>

{% endblock content %}